using GDMAmpAccessible.Models;

namespace GDMAmpAccessible.Persistence;

internal static class FactoryPresetBank
{
    public static IReadOnlyList<UserPreset> Presets { get; } = Create();

    private static UserPreset P(string code, string name, ScenePreset sound) => new()
    {
        Name = $"{code} - {name}",
        Sound = sound,
        NamEnabled = false,
        PreEffectOrder = UserPreset.DefaultOrder()
    };

    private static List<UserPreset> Create() => new()
    {
        P("F01","Twin Clean", new ScenePreset { Channel=AmpChannel.CleanTwin, Gain=2.2f, OutputPercent=40f, Bass=4.8f, Middle=3.8f, Treble=6.5f, Presence=6.0f, CompressorEnabled=true, CompressorCharacter=CompressorCharacter.StudioClean, CompressorSustain=2.8f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Spring, ReverbMixPercent=14f }),
        P("F02","Lone Star Clean", new ScenePreset { Channel=AmpChannel.CleanBoutique, Gain=3.8f, OutputPercent=39f, Bass=6.5f, Middle=6.2f, Treble=4.2f, Presence=3.8f, CompressorEnabled=true, CompressorCharacter=CompressorCharacter.Optical, CompressorSustain=4.8f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Room, ReverbMixPercent=24f }),
        P("F03","Class A Clean", new ScenePreset { Channel=AmpChannel.CleanClassA, Gain=3.7f, OutputPercent=41f, Bass=4.2f, Middle=6.4f, Treble=6.3f, Presence=6.0f, ChorusEnabled=true, ChorusCharacter=ChorusCharacter.Dimension, ChorusMixPercent=55f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Room, ReverbMixPercent=20f }),
        P("F04","Studio Chorus Clean", new ScenePreset { Channel=AmpChannel.CleanTwin, Gain=2.4f, OutputPercent=72f, CompressorEnabled=true, CompressorCharacter=CompressorCharacter.StudioClean, CompressorSustain=5.0f, CompressorLevel=5.6f, ChorusEnabled=true, ChorusCharacter=ChorusCharacter.Ensemble, ChorusRateHz=0.85f, ChorusDepthMs=5.0f, ChorusMixPercent=58f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Plate, ReverbMixPercent=22f }),
        P("F05","Worship Dotted Clean", new ScenePreset { Channel=AmpChannel.CleanBoutique, Gain=3.0f, OutputPercent=45f, CompressorEnabled=true, CompressorCharacter=CompressorCharacter.Optical, CompressorSustain=4.5f, DelayEnabled=true, DelaySyncEnabled=true, DelayDivision=TempoDivision.DottedEighth, DelayCharacter=DelayCharacter.DigitalClean, DelayFeedbackPercent=48f, DelayMixPercent=50f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Hall, ReverbMixPercent=42f, ReverbDecayPercent=72f }),
        P("F06","Ambient Church", new ScenePreset { Channel=AmpChannel.CleanTwin, Gain=2.5f, OutputPercent=46f, ChorusEnabled=true, ChorusCharacter=ChorusCharacter.Dimension, ChorusMixPercent=48f, DelayEnabled=true, DelaySyncEnabled=true, DelayDivision=TempoDivision.DottedEighth, DelayFeedbackPercent=46f, DelayMixPercent=46f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Church, ReverbMixPercent=46f, ReverbDecayPercent=82f, ReverbPreDelayMs=52f, ReverbDampingPercent=55f, ReverbDiffusionPercent=88f }),
        P("F07","Shimmer Worship", new ScenePreset { Channel=AmpChannel.CleanBoutique, Gain=2.7f, OutputPercent=47f, ChorusEnabled=true, ChorusCharacter=ChorusCharacter.Dimension, ChorusMixPercent=48f, DelayEnabled=true, DelaySyncEnabled=true, DelayDivision=TempoDivision.Quarter, DelayMixPercent=44f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Shimmer, ReverbMixPercent=66f, ReverbDecayPercent=90f, ReverbPreDelayMs=48f, ReverbDiffusionPercent=92f }),
        P("F08","Dimension Wide", new ScenePreset { Channel=AmpChannel.CleanClassA, Gain=2.7f, OutputPercent=43f, ChorusEnabled=true, ChorusCharacter=ChorusCharacter.Dimension, ChorusMixPercent=68f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Plate, ReverbMixPercent=22f }),
        P("F09","British Crunch", new ScenePreset { Channel=AmpChannel.CrunchBritish, Gain=5.8f, OutputPercent=38f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Room, ReverbMixPercent=12f }),
        P("F10","Plexi Classic", new ScenePreset { Channel=AmpChannel.CrunchPlexi, Gain=6.3f, OutputPercent=37f, BoosterEnabled=true, BoosterCharacter=BoosterCharacter.CaeLineDriver, BoosterDb=3f, ReverbEnabled=true, ReverbMixPercent=10f }),
        P("F11","Class A Crunch", new ScenePreset { Channel=AmpChannel.CrunchClassA, Gain=5.9f, OutputPercent=39f, Treble=5.8f, Presence=5.5f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Room, ReverbMixPercent=12f }),
        P("F12","Crunch TS808", new ScenePreset { Channel=AmpChannel.CrunchBritish, Gain=5.2f, OutputPercent=37f, Ts9Enabled=true, DriveCharacter=DriveCharacter.Ts808, Ts9Gain=4.2f, Ts9Level=7.2f, ReverbEnabled=true, ReverbMixPercent=12f }),
        P("F13","Klon Drive", new ScenePreset { Channel=AmpChannel.CleanBoutique, Gain=5.0f, OutputPercent=38f, Ts9Enabled=true, DriveCharacter=DriveCharacter.Klon, Ts9Gain=6.2f, Ts9Tone=5.8f, Ts9Level=6.8f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Plate, ReverbMixPercent=16f }),
        P("F14","DOD 250 Drive", new ScenePreset { Channel=AmpChannel.CrunchPlexi, Gain=5.2f, OutputPercent=37f, Ts9Enabled=true, DriveCharacter=DriveCharacter.Dod250, Ts9Gain=7.0f, Ts9Tone=5.4f, Ts9Level=6.5f, ReverbEnabled=true, ReverbMixPercent=12f }),
        P("F15","TS9 Lead", new ScenePreset { Channel=AmpChannel.LeadJcm800, Gain=6.6f, OutputPercent=34f, BoosterEnabled=true, BoosterCharacter=BoosterCharacter.CaeLineDriver, BoosterDb=3.2f, Ts9Enabled=true, DriveCharacter=DriveCharacter.Ts9, Ts9Gain=5.8f, Ts9Tone=5.0f, Ts9Level=6.8f, DelayEnabled=true, DelayTimeMs=360f, DelayFeedbackPercent=24f, DelayMixPercent=18f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Plate, ReverbMixPercent=18f }),
        P("F16","Marshall Drive", new ScenePreset { Channel=AmpChannel.CleanBoutique, Gain=3.7f, OutputPercent=38f, Ts9Enabled=true, DriveCharacter=DriveCharacter.Marshall, Ts9Gain=5.0f, Ts9Tone=5.3f, Ts9Level=5.3f, ReverbEnabled=true, ReverbMixPercent=14f }),
        P("F17","Warm Lead", new ScenePreset { Channel=AmpChannel.LeadJcm800, Gain=6.8f, OutputPercent=33f, BoosterEnabled=true, BoosterCharacter=BoosterCharacter.CaeLineDriver, BoosterDb=4.2f, OverdriveEnabled=true, DistortionCharacter=DistortionCharacter.Ds1, OverdriveGain=7.6f, OverdriveTone=4.6f, OverdriveLevel=5.7f, DelayEnabled=true, DelaySyncEnabled=true, DelayDivision=TempoDivision.Quarter, DelayFeedbackPercent=24f, DelayMixPercent=19f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Plate, ReverbMixPercent=20f }),
        P("F18","Legacy Singing Lead", new ScenePreset { Channel=AmpChannel.LeadLegacy, Gain=7.4f, OutputPercent=41f, Bass=4.6f, Middle=7.2f, Treble=4.4f, Presence=4.1f, BoosterEnabled=true, BoosterCharacter=BoosterCharacter.EpStyle, BoosterDb=1.8f, CompressorEnabled=true, CompressorCharacter=CompressorCharacter.Sustainer, CompressorSustain=4.7f, CompressorAttackMs=24f, CompressorLevel=5.2f, OverdriveEnabled=false, Ts9Enabled=true, DriveCharacter=DriveCharacter.Ts808, Ts9Gain=1.2f, Ts9Tone=4.3f, Ts9Level=6.3f, DelayEnabled=true, DelayTimeMs=410f, DelayFeedbackPercent=25f, DelayMixPercent=20f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Plate, ReverbMixPercent=19f, ReverbDecayPercent=56f }),
        P("F19","Modern Lead", new ScenePreset { Channel=AmpChannel.LeadModern, Gain=6.7f, OutputPercent=42f, GateEnabled=true, GateThresholdDb=-48f, GateReleaseMs=145f, BoosterEnabled=true, BoosterCharacter=BoosterCharacter.CaeLineDriver, BoosterDb=3.5f, OverdriveEnabled=true, DistortionCharacter=DistortionCharacter.Modern, OverdriveGain=7.8f, OverdriveTone=5.3f, OverdriveLevel=5.5f, Ts9Enabled=true, DriveCharacter=DriveCharacter.Ts808, Ts9Gain=1.2f, Ts9Level=6.0f, ReverbEnabled=true, ReverbMixPercent=13f }),
        P("F20","Singing Solo", new ScenePreset { Channel=AmpChannel.LeadLegacy, Gain=7.2f, OutputPercent=43f, BoosterEnabled=true, BoosterCharacter=BoosterCharacter.EpStyle, BoosterDb=4.8f, CompressorEnabled=true, CompressorCharacter=CompressorCharacter.Sustainer, CompressorSustain=5.8f, OverdriveEnabled=true, DistortionCharacter=DistortionCharacter.Ds1, OverdriveGain=8.2f, OverdriveTone=4.5f, OverdriveLevel=5.8f, DelayEnabled=true, DelaySyncEnabled=true, DelayDivision=TempoDivision.DottedEighth, DelayFeedbackPercent=30f, DelayMixPercent=24f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Hall, ReverbMixPercent=23f }),
        P("F21","Leslie Clean", new ScenePreset { Channel=AmpChannel.CleanBoutique, Gain=2.8f, OutputPercent=51f, RotaryEnabled=true, RotaryFast=true, RotaryDepthPercent=100f, RotaryMixPercent=86f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Room, ReverbMixPercent=16f }),
        P("F22","Jet Flanger", new ScenePreset { Channel=AmpChannel.CleanClassA, Gain=3.0f, OutputPercent=52f, FlangerEnabled=true, FlangerCharacter=FlangerCharacter.Jet, FlangerDepthPercent=100f, FlangerFeedbackPercent=66f, FlangerMixPercent=82f, ReverbEnabled=true, ReverbMixPercent=14f }),
        P("F23","Tape Delay", new ScenePreset { Channel=AmpChannel.CleanBoutique, Gain=3.2f, OutputPercent=52f, DelayEnabled=true, DelayCharacter=DelayCharacter.Tape, DelayTimeMs=540f, DelayFeedbackPercent=56f, DelayMixPercent=54f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Plate, ReverbMixPercent=18f }),
        P("F24","Ambient Lead", new ScenePreset { Channel=AmpChannel.LeadLegacy, Gain=5.2f, OutputPercent=52f, ChorusEnabled=true, ChorusCharacter=ChorusCharacter.Dimension, ChorusMixPercent=32f, DelayEnabled=true, DelaySyncEnabled=true, DelayDivision=TempoDivision.DottedEighth, DelayFeedbackPercent=36f, DelayMixPercent=32f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Cathedral, ReverbMixPercent=42f, ReverbDecayPercent=86f, ReverbPreDelayMs=78f, ReverbDampingPercent=58f, ReverbDiffusionPercent=94f })
,
        P("F25","Hammond Leslie", new ScenePreset { Channel=AmpChannel.CleanBoutique, Gain=2.15f, Bass=4.6f, Middle=6.4f, Treble=4.6f, Presence=3.8f, OutputPercent=57f, CompressorEnabled=true, CompressorCharacter=CompressorCharacter.Sustainer, CompressorSustain=7.4f, CompressorAttackMs=12f, CompressorLevel=5.8f, OctaverEnabled=true, OctaverCharacter=OctaverCharacter.Organ, OctaverDryPercent=18f, OctaverDownPercent=46f, OctaverUpPercent=58f, OctaverTonePercent=57f, OctaverLevelPercent=96f, RotaryEnabled=true, RotaryFast=true, RotaryDepthPercent=96f, RotaryMixPercent=88f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Room, ReverbMixPercent=12f, ReverbDecayPercent=34f, ReverbPreDelayMs=8f }),
        P("F26","Octave Lead", new ScenePreset { Channel=AmpChannel.LeadLegacy, Gain=6.4f, OutputPercent=52f, OctaverEnabled=true, OctaverCharacter=OctaverCharacter.Up, OctaverDryPercent=78f, OctaverUpPercent=24f, OctaverTonePercent=54f, OctaverLevelPercent=96f, BoosterEnabled=true, BoosterCharacter=BoosterCharacter.EpStyle, BoosterDb=3.5f, DelayEnabled=true, DelayTimeMs=360f, DelayMixPercent=17f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Plate, ReverbMixPercent=18f }),
        P("F27","Sub Octave Clean", new ScenePreset { Channel=AmpChannel.CleanBoutique, Gain=2.6f, OutputPercent=55f, OctaverEnabled=true, OctaverCharacter=OctaverCharacter.Sub, OctaverDryPercent=58f, OctaverDownPercent=70f, OctaverTonePercent=28f, OctaverLevelPercent=94f, CompressorEnabled=true, CompressorCharacter=CompressorCharacter.Optical, CompressorSustain=4.8f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Room, ReverbMixPercent=12f }),
        P("F28","Auto Wah Funk", new ScenePreset { Channel=AmpChannel.CleanTwin, Gain=2.6f, OutputPercent=50f, Bass=4.4f, Middle=5.6f, Treble=6.2f, Presence=5.8f, AutoWahEnabled=true, AutoWahSensitivity=8.2f, AutoWahRange=7.4f, AutoWahResonance=7.6f, GateEnabled=true, GateThresholdDb=-62f, GateReleaseMs=210f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Spring, ReverbMixPercent=10f }),
        P("F29","Vintage Phaser Crunch", new ScenePreset { Channel=AmpChannel.CrunchPlexi, Gain=4.7f, OutputPercent=44f, Bass=5.0f, Middle=6.3f, Treble=5.0f, Presence=4.8f, PhaserEnabled=true, PhaserRateHz=0.55f, PhaserDepthPercent=78f, PhaserFeedbackPercent=25f, PhaserMixPercent=58f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Room, ReverbMixPercent=12f }),
        P("F30","Tremolo Worship", new ScenePreset { Channel=AmpChannel.CleanBoutique, Gain=3.1f, OutputPercent=47f, Bass=5.2f, Middle=5.4f, Treble=5.6f, Presence=5.0f, CompressorEnabled=true, CompressorCharacter=CompressorCharacter.Optical, CompressorSustain=4.2f, CompressorAttackMs=24f, CompressorLevel=5.1f, TremoloEnabled=true, TremoloSyncEnabled=true, TremoloDivision=TempoDivision.Eighth, TremoloDepthPercent=58f, DelayEnabled=true, DelaySyncEnabled=true, DelayDivision=TempoDivision.DottedEighth, DelayCharacter=DelayCharacter.DigitalClean, DelayFeedbackPercent=32f, DelayMixPercent=26f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Hall, ReverbMixPercent=30f, ReverbDecayPercent=70f }),
        P("F31","Steve Vai Legacy Clean", new ScenePreset { Channel=AmpChannel.CleanBoutique, Gain=3.0f, OutputPercent=47f, Bass=7.2f, Middle=6.8f, Treble=7.0f, Presence=5.8f, GateEnabled=true, GateThresholdDb=-62f, GateReleaseMs=220f, CompressorEnabled=true, CompressorCharacter=CompressorCharacter.Optical, CompressorSustain=3.8f, CompressorAttackMs=24f, CompressorLevel=5.1f, ChorusEnabled=true, ChorusPlacement=ChorusPlacement.Loop, ChorusCharacter=ChorusCharacter.Dimension, ChorusRateHz=0.55f, ChorusDepthMs=4.2f, ChorusMixPercent=22f, DelayEnabled=true, DelayCharacter=DelayCharacter.DigitalClean, DelayTimeMs=360f, DelayFeedbackPercent=18f, DelayMixPercent=14f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Plate, ReverbMixPercent=14f, ReverbDecayPercent=46f, ReverbTonePercent=58f, ReverbPreDelayMs=20f, ReverbDampingPercent=42f, ReverbDiffusionPercent=68f }),
        P("F32","Steve Vai Legacy Lead", new ScenePreset { Channel=AmpChannel.LeadLegacy, Gain=6.2f, OutputPercent=44f, Bass=6.4f, Middle=6.2f, Treble=6.0f, Presence=5.4f, GateEnabled=true, GateThresholdDb=-54f, GateReleaseMs=175f, CompressorEnabled=true, CompressorCharacter=CompressorCharacter.Sustainer, CompressorSustain=4.6f, CompressorAttackMs=22f, CompressorLevel=5.2f, BoosterEnabled=true, BoosterCharacter=BoosterCharacter.EpStyle, BoosterDb=1.5f, AutoWahEnabled=false, AutoWahMode=AutoWahMode.ManualExpression, AutoWahCharacter=AutoWahCharacter.VaiBadHorsie, AutoWahSensitivity=5.5f, AutoWahRange=6.0f, AutoWahResonance=6.4f, Ts9Enabled=true, DriveCharacter=DriveCharacter.Ts808, Ts9Gain=0.9f, Ts9Tone=4.6f, Ts9Level=6.2f, DelayEnabled=true, DelayCharacter=DelayCharacter.DigitalClean, DelayTimeMs=405f, DelayFeedbackPercent=25f, DelayMixPercent=20f, ReverbEnabled=true, ReverbCharacter=ReverbCharacter.Plate, ReverbMixPercent=17f, ReverbDecayPercent=52f, ReverbTonePercent=54f, ReverbPreDelayMs=24f, ReverbDampingPercent=48f, ReverbDiffusionPercent=72f })
    };
}
